# 开发环境配置
server:
  port: 8001
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influx:
    url: http://192.168.5.100:8086
    user: flying
    password: influxdb_MWR5TP
    bucket: program
    organization: flyingcoding
  mail:
    host: smtp.163.com
    username: javaweb111@163.com
    password: UMUNGOCGACNHANOL
    port: 465
    properties:
      from: javaweb111@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    port: 5672
    addresses: 192.168.5.100
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  datasource:
    url: jdbc:mysql://192.168.5.100:3306/monitor
    username: monitor
    password: SwCe6mbRBwks6G6d
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: 192.168.5.100
      port: 6379
      username: default
      password: redis_EHb2Yc
  security:
    jwt:
      key: 'monitor-key'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
