# 开发环境配置
server:
  port: 8001
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influx:
    url: ${INFLUX_URL:http://192.168.5.100:8086}
    user: ${INFLUX_USER:flying}
    password: ${INFLUX_PASSWORD:influxdb_MWR5TP}
    bucket: ${INFLUX_BUCKET:program}
    organization: ${INFLUX_ORG:flyingcoding}
  mail:
    host: ${MAIL_HOST:smtp.163.com}
    username: ${MAIL_USERNAME:javaweb111@163.com}
    password: ${MAIL_PASSWORD:UMUNGOCGACNHANOL}
    port: ${MAIL_PORT:465}
    properties:
      from: ${MAIL_FROM:javaweb111@163.com}
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    addresses: ${RABBITMQ_HOST:192.168.5.100}
    username: ${RABBITMQ_USER:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2
        default-requeue-rejected: false
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.5.100:3306/monitor}
    username: ${MYSQL_USER:monitor}
    password: ${MYSQL_PASSWORD:SwCe6mbRBwks6G6d}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:192.168.5.100}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:redis_EHb2Yc}
  security:
    jwt:
      key: ${JWT_KEY:monitor-key}
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
management:
  endpoints:
    web:
      exposure:
        include: health
